#include "web_pages.h"

/*******************************************************************************
 * Embedded files provided by CMake `EMBED_TXTFILES` - symbols are generated as:
 * _binary_<path>_start/_end where slashes/dots are replaced with underscores.
 ******************************************************************************/
/* Symbols generated by EMBED_TXTFILES use the filename (slashes/dots removed),
   e.g. "www/index.html" -> _binary_index_html_start/_end */
extern const char _binary_index_html_start[] asm ("_binary_index_html_start");
extern const char _binary_index_html_end[]   asm ("_binary_index_html_end");
extern const char _binary_main_js_start[]    asm ("_binary_main_js_start");
extern const char _binary_main_js_end[]      asm ("_binary_main_js_end");

const web_page_t WEB_PAGES[] =
{
    {
        .uri = "/",
        .content_start = _binary_index_html_start,
        .content_end = _binary_index_html_end,
        .content_type = "text/html"
    },
    {
        .uri = "/main.js",
        .content_start = _binary_main_js_start,
        .content_end = _binary_main_js_end,
        .content_type = "application/javascript"
    }
};

const size_t WEB_PAGES_COUNT = (sizeof(WEB_PAGES) / sizeof(WEB_PAGES[0]));

